language: python
python:
  - "3.5"
env:
  - DJANGO_SETTINGS_MODULE=autostew.settings.dev
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - ./recreate_db.sh
  - coverage run --branch --source . manage.py test

notifications:
  email:
    recipients:
      - witmic1@gmail.com
      - joan.ardiaca@gmail.com
    on_success: change
    on_failure: always

after_success: coveralls
